version: '3'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloudships
    volumes:
      - dev_data:/var/lib/postgresql/data
  web:
    build: .
    environment:
        DEBUG: "true"
        DATABASE_URL: postgres://postgres:password@db:5432/cloudships
        GS_BUCKET_NAME:
        CURRENT_HOST: localhost
        SECRET_KEY: a-secret-key
    command: python manage.py runserver 0.0.0.0:8080
    working_dir: /app/code
    volumes:
      - .:/app/code
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
    dev_data:
