version: '3'

services:
  db:
    image: postgres:11.1
    environment:
      POSTGRES_PASSWORD: cloudships
      POSTGRES_DB: cloudships
    volumes:
      - pg_data:/var/lib/postgresql/data
  django:
    build: .
    environment:
        DEBUG: "true"
        DATABASE_URL: postgres://postgres:cloudships@db:5432/cloudships
        SECRET_KEY: a-secret-key
        PORT: 8645
    command: python manage.py runserver 0.0.0.0:8645
    working_dir: /app/code
    volumes:
      - .:/app/code
    ports:
      - "8645:8645"
    depends_on:
      - db

volumes:
    pg_data:
