# Generated by Django 3.0.4 on 2020-05-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloudships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameplayer",
            name="state",
            field=models.CharField(
                choices=[("playing", "Playing"), ("finished", "Finished"), ("dnf", "Dnf")],
                default="playing",
                max_length=16,
            ),
        ),
    ]
