# Generated by Django 3.0.4 on 2020-05-08 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloudships", "0002_add_player_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameconfig", name="count", field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name="gameconfig",
            name="player_1",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cloudships.BotServer",
            ),
        ),
        migrations.AddField(
            model_name="gameconfig",
            name="player_2",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="cloudships.BotServer",
            ),
        ),
    ]
