# Generated by Django 3.0.4 on 2020-05-08 01:12

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cloudships', '0002_add_player_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now(), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='name',
            field=models.CharField(default='CHANGEME', max_length=255),
            preserve_default=False,
        ),
    ]
