steps:
  - id: "build"
    name: "gcr.io/cloud-builders/docker"
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/example-client
      - --build-arg
      - PRODUCTION=1
      - .
  - id: "push"
    name: "gcr.io/cloud-builders/docker"
    args:
      - push
      - gcr.io/$PROJECT_ID/example-client
  - id: "deploy"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      - run
      - deploy
      - example-client
      - --platform
      - managed
      - --allow-unauthenticated
      - --max-instances
      - "10"
      - --region
      - asia-northeast1
      - --image
      - gcr.io/$PROJECT_ID/example-client
