steps:
    - id: 'build and push'
      name: 'gcr.io/kaniko-project/executor:latest'
      args:
        - --destination=gcr.io/$PROJECT_ID/battleships-app
        - --cache=true
        - --build-arg
        - PRODUCTION=1
    - id: 'migrate'
      name: 'gcr.io/google-appengine/exec-wrapper'
      args:
        - -i
        - gcr.io/$PROJECT_ID/battleships-app
        - -s
        - $PROJECT_ID:asia-northeast1:battleships-db
        - -e
        - PROJECT_ID=$PROJECT_ID
        - --
        - sh
        - .cloudbuild/migrate.sh
    - id: 'deploy'
      name: 'gcr.io/cloud-builders/gcloud'
      args:
        - run
        - deploy
        - battleships-app
        - --platform
        - managed
        -  --region
        - asia-northeast1
        - --image
        - gcr.io/$PROJECT_ID/battleships-app
