steps:
    - id: 'build'
      name: 'gcr.io/cloud-builders/docker'
      args:
        - build
        - -t
        - gcr.io/$PROJECT_ID/the_carlsen_approach
        - --build-arg
        - PRODUCTION=1
        - .
    - id: 'push'
      name: 'gcr.io/cloud-builders/docker'
      args:
        - push
        - gcr.io/$PROJECT_ID/the_carlsen_approach
    - id: 'deploy'
      name: 'gcr.io/cloud-builders/gcloud'
      args:
        - run
        - deploy
        - the-carlsen-approach
        - --platform
        - managed
        -  --region
        - asia-northeast1
        - --image
        - gcr.io/$PROJECT_ID/the_carlsen_approach
